experiments:
  toy_1d:
    problem:
      name: Toy1DProblem
    optimizers:
      scipy_optimize_minimize:
        name: scipy_optimize_minimize
        args:
          x0:
            - 2.0  # close to solution
        kwargs:
          bounds:
            -
              - -5.0
              - 5.0
          options:
            maxiter: 100
      scipy_minimize_rand_init:
        name: scipy_minimize_rand_init
        args:
          init_range:
            -
              - -2.0
              - 2.0
        kwargs:
          bounds:
            -
              - -5.0
              - 5.0
          options:
            maxiter: 100
        n_trials: 100
      lpfgopt_minimize:
        name: lpfgopt_minimize
        args:
          bounds:
            -
              - -5.0
              - 5.0
        kwargs:
          maxit: 100
        n_trials: 100
      lpfgopt_minimize_rand_init:
        name: lpfgopt_minimize_rand_init
        args:
          bounds:
            -
              - -5.0
              - 5.0
        kwargs:
          init_range:
            -
              - -2.0
              - 2.0
          maxit: 100
        n_trials: 100
      skopt_gp_minimize:
        name: skopt_gp_minimize
        args:
          dimensions:
            - type: real
              name: x
              low: -5.0
              high: 5.0
              prior: uniform
        kwargs:
          n_calls: 50
          noise: 0.0
          n_initial_points: 10
        n_trials: 10
  sys_id_fopdt:
    problem:
      name: SysIdFromFileFOPDT
      args:
        bounds: 
          -
            - -86.00479336990831
            - 86.00479336990831
          -
            - 15.08
            - 4406.4
          -
            - 0.0
            - 88.0
          -
            - 390.7399912087402
            - 609.27040320874
          -
            - 474.7938764
            - 584.0590823999999
        dt: 15.08
        io_data_path: problems/sys_id_fopdt/data/io_data_fopdt.csv
        u_label: Input1
        y_label: Output
      kwargs:
        u_base: 5.0
    optimizers:
      lpfgopt_minimize:
        name: lpfgopt_minimize
        args:
          bounds:
            -
              - -86.00479336990831
              - 86.00479336990831
            -
              - 15.08
              - 4406.4
            -
              - 0
              - 88
            -
              - 390.7399912087402
              - 609.27040320874
            -
              - 474.7938764
              - 584.0590823999999
        kwargs:
          discrete:
            - 2
          points: 50
          tol: 0.01
          maxit: 1000
        n_trials: 100
      skopt_gp_minimize:
        name: skopt_gp_minimize
        args:
          dimensions:
            - type: real
              name: K
              low: -86.00479336990831
              high: 86.00479336990831
              prior: uniform
            - type: real
              name: tau
              low: 15.08
              high: 4406.4
              prior: uniform
            - type: integer
              name: theta
              low: 0
              high: 88
              prior: uniform
            - type: real
              name: y_base
              low: 390.7399912087402
              high: 609.27040320874
              prior: uniform
            - type: real
              name: y_init
              low: 474.7938764
              high: 584.0590823999999
              prior: uniform
        kwargs:
          n_calls: 250
          noise: 0.0
          n_initial_points: 10
        n_trials: 20
  sys_id_fopdt_real_delay:
    problem:
      name: SysIdFromFileFOPDTRealDelay
      args:
        bounds: 
          -
            - -86.00479336990831
            - 86.00479336990831
          -
            - 15.08
            - 4406.4
          -
            - 0.0
            - 1327.04
          -
            - 390.7399912087402
            - 609.27040320874
          -
            - 474.7938764
            - 584.0590823999999
        dt: 15.08
        io_data_path: problems/sys_id_fopdt/data/io_data_fopdt.csv
        u_label: Input1
        y_label: Output
      kwargs:
        u_base: 5.0
    optimizers:
      lpfgopt_minimize_rand_init:
        name: lpfgopt_minimize_rand_init
        args:
          bounds:
            -
              - -86.00479336990831
              - 86.00479336990831
            -
              - 15.08
              - 4406.4
            -
              - 0.0
              - 1327.04
            -
              - 390.7399912087402
              - 609.27040320874
            -
              - 474.7938764
              - 584.0590823999999
        kwargs:
          init_range:
            -
              - -12.0
              - -8.0
            -
              - 150.0
              - 200.0
            -
              - 150.0
              - 250.0
            -
              - 470.0
              - 500.0
            -
              - 470.0
              - 490.0
          points: 50
          tol: 0.01
          maxit: 1000
        n_trials: 100
      skopt_gp_minimize:
        name: skopt_gp_minimize
        args:
          dimensions:
            - type: real
              name: K
              low: -86.00479336990831
              high: 86.00479336990831
              prior: uniform
            - type: real
              name: tau
              low: 15.08
              high: 4406.4
              prior: uniform
            - type: real
              name: theta
              low: 0.0
              high: 1327.04
              prior: uniform
            - type: real
              name: y_base
              low: 390.7399912087402
              high: 609.27040320874
              prior: uniform
            - type: real
              name: y_init
              low: 474.7938764
              high: 584.0590823999999
              prior: uniform
        kwargs:
          n_calls: 250
          noise: 0.0
          n_initial_points: 10
        n_trials: 10
