experiments:
  toy_1d:
    problem:
      name: Toy1DProblem
    optimizers:
      scipy.optimize.minimize:
        name: scipy_optimize_minimize
        args:
          x0:
            - 2.0
      lpfgopt.minimize:
        name: lpfgopt_minimize
        args:
          bounds:
            -
              - -5.0
              - 5.0
      skopt_gp_minimize:
        name: skopt_gp_minimize
        args:
          dimensions:
            -
              - -5.0
              - 5.0
        kwargs:
          n_calls: 50
          noise: 0.0
          n_initial_points: 10
